### ISSUE TITLE
Doesn't start on Linux

### ISSUE THREAD

**Issue by qubodup** [Panda3D-google-code-repositories/arcns#1]
Hello, I tried running this on Arch Linux 64bit but this happens:

<pre>$ python2 arcns.py 
Using deprecated DirectStart interface.
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
:display:x11display(error): BadMatch (invalid parameter attributes)
Traceback (most recent call last):
  File "arcns.py", line 629, in <module>
    app = ArcnsApp()
  File "arcns.py", line 574, in __init__
    self.main_config = json.loads("".join([line.rstrip().lstrip() for line in file(self.curdir+"/config.json","rb")]))
  File "/usr/share/panda3d/direct/stdpy/file.py", line 139, in __init__
    raise IOError, message
IOError: No such file: ../config.json</pre>

`touch ../config.json` causes

<pre>$ python2 arcns.py 
Using deprecated DirectStart interface.
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
:display:x11display(error): BadMatch (invalid parameter attributes)
Traceback (most recent call last):
  File "arcns.py", line 629, in <module>
    app = ArcnsApp()
  File "arcns.py", line 574, in __init__
    self.main_config = json.loads("".join([line.rstrip().lstrip() for line in file(self.curdir+"/config.json","rb")]))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded</pre>

**Comment by frainfreeze** [comment]
There is a missing file.

```
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
Traceback (most recent call last):
  File "arcns.py", line 629, in <module>
    app = ArcnsApp()
  File "arcns.py", line 574, in __init__
    self.main_config = json.loads("".join([line.rstrip().lstrip() for line in file(self.curdir+"/config.json","rb")]))
  File "/usr/share/panda3d/direct/stdpy/file.py", line 139, in __init__
    raise IOError, message
IOError: No such file: ../config.json

```
